# Generated by Django 4.2.1 on 2023-06-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_finch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='diet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finch',
            name='lifespan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finch',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finch',
            name='species',
            field=models.CharField(max_length=50),
        ),
    ]
